# Generated by Django 4.1.1 on 2022-09-27 10:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('birthdate', models.DateField(default=datetime.date.today)),
                ('email', models.CharField(max_length=500)),
                ('street', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('zip', models.IntegerField()),
                ('region', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('productCategory', models.CharField(choices=[('digital', 'Digital Products'), ('healthcare', 'Healthcare'), ('household', 'Household'), ('sport', 'Sport')], default='digital', max_length=20)),
                ('sales', models.FloatField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
                ('salesPerson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.salesperson')),
            ],
        ),
    ]
