# Generated by Django 4.1.1 on 2022-09-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.CharField(choices=[('china', 'China'), ('germany', 'Germany'), ('us', 'USA'), ('fr', 'Frankreich')], default='digital', max_length=20),
        ),
    ]
